### ISSUE TITLE
updateTab with null newTab data failing

### ISSUE THREAD

**Issue by adityatoshniwal** [ticlo/rc-dock#123]
Hi,

I'm trying to focus and make a tab active using the docker instance. 
As per https://github.com/ticlo/rc-dock/blob/454f03af5f9e729a3e11857dfa8a29ac2febbd92/lib/DockData.d.ts#L290, one can make a tab active by passing newTab as null. But it fails with error
Cannot read properties of null (reading 'id')
    at DockLayout.updateTab (DockLayout.js:282)

Am I missing something ? Should I raise a PR ?

**Comment by adityatoshniwal** [comment]
I also tried - docker.current.dockMove(docker.current.find(panelId), null, 'active');

**Comment by rinick** [comment]
fixed in @3.2.3

**Comment by adityatoshniwal** [comment]
Cool !! Thanks for the great work.

**Comment by adityatoshniwal** [comment]
I still can't get the tab to focus. I debugged the updateTab function and it is doing nothing. How can use rc-dock instance to make a tab active ?

**Comment by rinick** [comment]
sorry, the last fix only fixed the runtime error, didn't realize the feature itself was also broken.
Could you check 3.2.4 and see if it works now?

**Comment by adityatoshniwal** [comment]
Hey @rinick, I can confirm it works on 3.2.4 :)
Thanks a lot !!
